### ISSUE TITLE
Xiaomi Band 2

### ISSUE THREAD

**Issue by TwanoO67** [dkhmelenko/miband-android#1]
Hello!

Is this SDK compatible with the xiaomi band 2 ?
I'm looking for classes that could achieve to send "text" on the band 2 screen

**Comment by dkhmelenko** [comment]
For now it's only for the first version of Xiaomi band.
Support for the band 2 will be added later.

**Comment by TSG9876** [comment]
Hi, 

To support miband2  heart rate function you may need to add or change   miband sdk  from data[0]==6 add/to  **data[0]==0;**


In the protocol coding  ,original 
public static final byte[] START_HEART_RATE_SCAN = {21, 2, 1} only read once   base on test , there are suggestion for multiple read this may be {21,1,1} for miband 2 or miband pulse.


public void setHeartRateScanListener(final HeartRateNotifyListener listener) {
        mBluetoothIO.setNotifyListener(Profile.UUID_SERVICE_HEARTRATE, Profile.UUID_NOTIFICATION_HEARTRATE, data -> {
            Log.d(TAG, Arrays.toString(data));
            if (## **data.length == 2 && data[0] == 6**) {
                int heartRate = data[1] & 0xFF;
                listener.onNotify(heartRate);
            }
        });
}
