### ISSUE TITLE
Documentation on how to use.

### ISSUE THREAD

**Issue by AlexanderVladimirov9090** [dkhmelenko/miband-android#3]
Would be good to have example somewhere on how to use. This way would be more friendly to developers who want to use it.

**Comment by boanergepro** [comment]
Por favor podría colaborarnos con documentación.?

**Comment by aleperno** [comment]
Would love to see this. Specially for devs who are unfamiliar with android but want to jump in (like myself).

**Comment by dkhmelenko** [comment]
This issue is finally closed. Some basic information on how to use is available in README.md
